version: '3.9'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.29.0
    container_name: jaeger
    ports:
      - 6831:6831/udp
      - 16686:16686
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
    networks:
      - observability-net
  restaurants:
    build:
      context: .
      dockerfile: Dockerfile.dev
    stop_signal: SIGINT
    ports:
      - '8000:8000'
    networks:
      - observability-net
  opentelemetry-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: opentelemetry-collector
    volumes:
      - ./config/config.yml/:/etc/opentelemetry-collector.yml
    command:
      - "--config=/etc/opentelemetry-collector.yml"
    ports:
      - 4317:4317
      - 13133:13133
      - 8889:8889
    networks:
      - observability-net
    depends_on:
      - jaeger
networks:
  observability-net: