openapi: 3.0.0
info:
  title: "Store api"
  description: "An API about managing stores"
  version: "1.0.0"
servers:
  - url: "/api"
paths:
  /stores/create:
    post:
      operationId: api.StoreView.post
      tags:
        - "Store"
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/Store'
      responses:
        "201":
          description: "Successfully created the store"
  '/stores/{store_id}':
    get:
      operationId: api.StoreView.get
      tags:
        - "Store"
      responses:
        "200":
          description: "Store found"
      parameters:
        - in: path
          name: store_id
          schema:
            type: string
          required: true
          description: id of the store (uuid)
    put:
      operationId: api.StoreView.put
      tags:
        - "Store"
      responses:
        "200":
          description: "Successfully updated the store"
    delete:
      operationId: api.StoreView.delete
      tags:
        - "Store"
      responses:
        "200":
          description: "Successfully deleted the store"
  /items/create:
    post:
      operationId: api.ItemView.post
      tags:
        - "Item"
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/Item'
      responses:
        "201":
          description: "Successfully created an item"
components:
  schemas:
    Store:
      type: object
      properties:
        name:
          type: string
    Item:
      type: object
      properties:
        name:
          type: string
        price:
          type: integer
        store_id:
          type: string
          format: uuid