openapi: 3.0.0
info:
  title: "Store api"
  description: "An API about managing stores"
  version: "1.0.0"
servers:
  - url: "/api"
paths:
  /stores:
    get:
      operationId: "store.list"
      tags:
        - "Store"
      summary: "Read the list of stores"
      responses:
        "200":
          description: "Successfully read stores list"
    post:
      operationId: "store.create"
      tags:
        - "Store"
      summary: "Create a store"
      responses:
        "200":
          description: "Successfully create the store"
  /stores/{name}/createItem:
    post:
      operationId: "store.create_item"
      parameters:
        - in: path
          name: name
          schema:
            type: string
          required: true
          description: name of the store
      tags:
        - "Store"
      summary: "create an item associated to the store"
      responses:
        "201":
          description: "Successfully created and linked the item to the store"
  /stores/{name}/items:
    get:
      operationId: "store.get_items_in_store"
      parameters:
        - in: path
          name: name
          schema:
            type: string
          required: true
          description: name of the store
      tags:
        - "Store"
      summary: "Get items of a specific store"
      responses:
        "201":
          description: "Successfully found items"
  /stores/{name}:
    get:
      operationId: "store.get_store_by_name"
      parameters:
        - in: path
          name: name
          schema:
            type: string
          required: true
          description: name of the store
      tags:
        - "Store"
      summary: "Get a store by name"
      responses:
        "200":
          description: "Successfully found the store"